### ISSUE TITLE
Encryption support?

### ISSUE THREAD

**Issue by mattn** [karlseguin/pg.zig#10]
I hope to use this pg.zig with encryption.

**Comment by karlseguin** [comment]
Do you mean connecting using TLS?

It currently isn't supported, but it's something I'd be willing to look at adding. However, I would use `std.crypto.tls.Client`  which (a) only supports TLS 1.3 and (b) is very buggy. I could add support though and hope that the issues in `std` eventually get fixed.

**Comment by karlseguin** [comment]
There's now a [tls branch](https://github.com/karlseguin/pg.zig/tree/tls)

The `connect` takes two new parameter: 

```zig
tls: bool = false, 
ca_bundle: ?std:crypto.Certificate.Bundle = null,
```
If `ca_bundle` is null when `tls = true`, a default bundle is created. This can be expensive if you're creating many connections directly. When done via the pool, a single bundle is shared for all connections (I probably need to add code to periodically `rescan` the bundle).

I wasn't able to get tests to work with it. I kept getting a `error.CertificateSignatureInvalid`...maybe there's something wrong with my self-signed certs. However, I did setup a quick `neon.tech` database (the first thing that showed up when I googled for a free hosted PostgreSQL) and it worked fine using the default OS bundle.

This won't be merged until `std.crypto.tls.Client` is fixed (see: https://github.com/ziglang/zig/issues/15226) I consider it dangerous to use given that it can be random (or maybe it's encrypted data that it fails to decrypt, I don't know) into the buffer without any way to know.

**Comment by mattn** [comment]
Oh, I'm surprising your quickly work. I'll look into it. Thanks.

**Comment by mattn** [comment]
Oh, I'm already using your zig-0.11 branch, but it's not easy to merge tls branch into zig-0.11 branch.

**Comment by karlseguin** [comment]
I added tls support directly into the zig-0.11 branch, easier to do now that the code is fresh in my mind.

**Comment by mattn** [comment]
```
$ LANG=C PGSSLMODE=require psql -h 10.0.10.70 -U postgres zig-nostr-relay
psql (15.6 (Ubuntu 15.6-1.pgdg22.04+1), server 14.10)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)
Type "help" for help.

zig-nostr-relay=> 
```

I'm trying to connect the server but something wrong.

```zig
    std.debug.print("{s}\n", .{env.db_host});
    var pool = pg.Pool.init(allocator, .{ .size = 5, .connect = .{
        .port = env.db_port,
        .host = env.db_host,
        .tls = true,
    }, .auth = .{
        .database = env.db_database,
        .username = env.db_username,
        .password = env.db_password,
        .timeout = env.db_timeout,
    } }) catch return;
    defer pool.deinit();
```

```
$ DB_HOST=10.0.10.70 ./zig-out/bin/zig-nostr-relay 
10.0.10.70
error(pg): connect error: error.TlsAlertHandshakeFailure
```

**Comment by karlseguin** [comment]
I'm not sure, but `std.crypto.tls.Client` only supports TLS 1.3, and your psql connected using 1.2 so I'd assume that's the issue. Would be nice if Zig had payloads with its errors :/

**Comment by mattn** [comment]
std/crypto/tls/Client.tls:241
```
        const ct = d.decode(tls.ContentType);
```
This d.decode seem to return .alert in first time call.

**Comment by karlseguin** [comment]
If you have access to the pg server and can restart it, can you set `ssl_min_protocol_version = 'TLSv1.3'` just to see if that's the issue?

**Comment by mattn** [comment]
Unfortunately, this server is hosted on Oracle Cloud database service, so I can't update the parameter. But 
```
zig-nostr-relay=> SELECT name as "Parameter name", setting as value, short_desc FROM pg_settings WHERE name LIKE '%ssl%';
             Parameter name             |             value              |                         short_desc                         
----------------------------------------+--------------------------------+------------------------------------------------------------
 ssl                                    | on                             | Enables SSL connections.
 ssl_ca_file                            | /etc/opt/postgresql/ca.pem     | Location of the SSL certificate authority file.
 ssl_cert_file                          | /etc/opt/postgresql/server.crt | Location of the SSL server certificate file.
 ssl_crl_dir                            |                                | Location of the SSL certificate revocation list directory.
 ssl_crl_file                           |                                | Location of the SSL certificate revocation list file.
 ssl_key_file                           | /etc/opt/postgresql/server.pvk | Location of the SSL server private key file.
 ssl_library                            | OpenSSL                        | Shows the name of the SSL library.
 ssl_passphrase_command_supports_reload | off                            | Also use ssl_passphrase_command during server reload.
 ssl_prefer_server_ciphers              | on                             | Give priority to server ciphersuite order.
(9 行)
```
Value of the parameter may be default.

**Comment by karlseguin** [comment]
Like I said, Zig's TLS is pretty buggy and limited right now. I'd guess this PostgreSQL server doesn't support TLS 1.3. The "easiest" thing might be to build a proxy in another language.  

app -- plain/tls1.3 --> proxy -- tls 1.2 --> postgresql

**Comment by mattn** [comment]
I tried the proxy way using https://github.com/verlihub/tls-proxy

But still have same issue.
```
./proxy -hub 10.0.10.70:5432 -host 192.168.11.4:5432 -ip=false -ver 3 -log -buf 500 -wait 2s 
```
This proxy works fine with psql but does not work with pg.zig.

**Comment by karlseguin** [comment]
I also didn't get it to work with tls-proxy, but I did get it to work with the following code. PostgreSQL's SSL works like StartTLS. First a non-encrypted connection is opened, the client sends a special 8-byte packet, and the server responds with a 1-byte ok/no. The connection can then be upgraded to TLS.

The code isn't super robust, but I wanted to get something that might work.


```go
package main

import (
	"bytes"
	"crypto/tls"
	"errors"
	"io"
	"log"
	"net"
	"sync"
)

const HOST = "ep-fancy-morning-a1hmgnby.ap-southeast-1.aws.neon.tech"

var SSLRequest = []byte{0, 0, 0, 8, 4, 210, 22, 47}

func main() {
	cer, err := tls.LoadX509KeyPair("hub.crt", "hub.key")
	if err != nil {
		log.Fatal(err)
		return
	}
	tlsConfig := &tls.Config{Certificates: []tls.Certificate{cer}, MinVersion: 3}

	listener, err := net.Listen("tcp", "localhost:5432")
	if err != nil {
		log.Fatal(err)
	}

	requestSSLBuffer := make([]byte, 8)
	for {
		client, err := listener.Accept()
		if err != nil {
			log.Println("accept: ", err)
			continue
		}

		if readRequestSSL(client, requestSSLBuffer) {
			// upgrade to TLS
			tlsClient := tls.Server(client, tlsConfig)
			if err := tlsClient.Handshake(); err != nil {
				log.Println("client Handshake:", err)
				client.Close()
				continue
			}

			tlsRemote, err := connectToRemote()
			if err != nil {
				log.Println("remote connection: ", err)
				client.Close()
				continue
			}

			go proxy(tlsClient, tlsRemote)
		}
	}
}

func readRequestSSL(client net.Conn, buf []byte) bool {
	pos := 0
	for pos != 8 {
		n, err := client.Read(buf[pos:])
		if n == 0 || err != nil {
			// TODO: Log?
			return false
		}
		pos += n
	}

	// the first message from the client should be an SSLRequest
	if bytes.Equal(buf, SSLRequest) == false {
		return false
	}

	// we tell the client that we accept the SSL request
	client.Write([]byte{'S'})
	return true
}

func connectToRemote() (net.Conn, error) {
	remote, err := net.Dial("tcp", HOST+":5432")
	if err != nil {
		return nil, err
	}

	if _, err := remote.Write(SSLRequest); err != nil {
		remote.Close()
		return nil, err
	}

	var buf [1]byte
	if _, err := remote.Read(buf[:]); err != nil {
		remote.Close()
		return nil, err
	}

	if buf[0] != 'S' {
		remote.Close()
		return nil, errors.New("Remote TLS Not Supported")
	}

	tlsRemote := tls.Client(remote, &tls.Config{ServerName: HOST})
	if err := tlsRemote.Handshake(); err != nil {
		return nil, err
	}
	return tlsRemote, nil
}

func proxy(client, remote net.Conn) {
	defer client.Close()
	defer remote.Close()

	var wg sync.WaitGroup
	wg.Add(2)

	go func() {
		defer wg.Done()
		io.Copy(client, remote)
		client.Close()
	}()

	go func() {
		defer wg.Done()
		io.Copy(remote, client)
		remote.Close()
	}()

	wg.Wait()
}
```

I generated the hub.key and hub.crt with:

```
openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out "hub.crt" -keyout "hub.key"
```

**Comment by mattn** [comment]
Hmm, I got `error(pg): connect error: error.CertificateHostMismatch`

**Comment by karlseguin** [comment]
There's no way to skip host verification with Zig's TLS. Weird that I didn't get the same issue. I re-issued the certs and used the following (maybe that's what I did the first time too):

```
openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out "hub.crt" -keyout "hub.key"  -subj '/CN=localhost'
```

**Comment by mattn** [comment]
Hmm, something wrong.
>error.TlsCertificateNotVerified

**Comment by karlseguin** [comment]
When you open the pool/connection, are you passing in a custom bundle?

```zig
    var bundle = std.crypto.Certificate.Bundle{};
    try bundle.addCertsFromFilePath(allocator, std.fs.cwd(), "hub.crt");
    defer bundle.deinit(allocator);

    var pool = try pg.Pool.init(allocator, .{
      .size = 5,
      .connect = .{
        .tls = true,
        .port = 5432,
        .host = "localhost",
        .ca_bundle = bundle,
      },
      .auth = .{
        .username = "blah",
        .database = "blah",
        .password = "blah",
      }
    });
    defer pool.deinit();
```

**Comment by mattn** [comment]
error.ConnectionResetByPeer and proxy generate error

> 2024/03/03 21:11:58 remote connection:  tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by karlseguin** [comment]
That's the Go code failing to verify the remote (oracle) cert. If you're in docker, maybe you need to install the root certs, or copy them over.

You could try changing:
```
tlsRemote := tls.Client(remote, &tls.Config{ServerName: HOST})
```

to
```
tlsRemote := tls.Client(remote, &tls.Config{InsecureSkipVerify: true})
```

But, as the name implies (i.e. "Insecure"), we're somewhat defeating the purpose of TLS at that point

**Comment by mattn** [comment]
Yes, now this way works. Thank you.

**Comment by mattn** [comment]
Do you have plan to merge pg.Stmt into zig-0.11 branch or tls into main branch?

**Comment by karlseguin** [comment]
I was able to cherry-pick the pg.Stmt branch into zig-0.11.

I think 0.12 is going to be released _very_ soon though, so I probably won't merge anything that presents challenges.

I don't plan on merging TLS until `std.crypto.tls.Client` isn't so broken.

**Comment by mattn** [comment]
Thank you.

**Comment by mattn** [comment]
Stmt is not exported from pg.zig ?

**Comment by karlseguin** [comment]
is now
