### ISSUE TITLE
Extend row.get() to handle iterator types, which in turn fixes row.to() to handle iterator columns

### ISSUE THREAD

**Issue by zigster64** [karlseguin/pg.zig#23]
The new `row.to()` function is very useful

Im using a number of Iterator([]const u8) fields in my structs, and I find that this small change to row.to() works for me :

```zig
        inline for (std.meta.fields(T)) |field| {
            switch (field.type) {
                Iterator([]const u8) => {
                    @field(result, field.name) = self.iterator([]const u8, columnIndex);
                },
                else => {
                    const value = self.get(field.type, columnIndex);
                    @field(result, field.name) = switch (field.type) {
                        []u8, []const u8 => if (allocator) |a| try a.dupe(u8, value) else value,
                        ?[]u8, ?[]const u8 => blk: {
                            const v = value orelse break :blk null;
                            break :blk if (allocator) |a| try a.dupe(u8, v) else v;
                        },
                        else => value,
                    };
                },
            }
            columnIndex += 1;
        }
```

I think looking at the more general solution - instead of expanding this out to cover every possible iterator, it might be cleaner to simply extend row.get(type, col)  to handle iterator field types.   

So   row.get(Iterator(T), col)  -> returns an Iterator(T)

The code for row.get() and row.iterator() is pretty close anyway - its just the decoder assignment that sets them apart

Doing that would also mean that row.iterator() becomes redundant

**Comment by karlseguin** [comment]
Do you really have `Iterator(T)` as your field type, so your struct value is only valid until the next `next()` ? I'd expect most people would have the slice, like `[]u32`, which would implicitly imply calling `alloc` on the iterator to create + populate a slice.

I guess both could be supported.

**Comment by zigster64** [comment]
yep - my struct has a field of type pg.Iterator(T)

General application of this (for me)  is im in a http handler, looping through query.next to get a row, then converting that row directly to HTML output via a template .. then onto the next row.

I never want to be cloning any columns out of the row for what Im currently doing.

This works out fine if you are 100% aware that you are dealing with very limited lifetimes on row values.  Sits well with htmx for example.  Might sound a bit awkward, but I think its a good performance-first, zero-allocation option.

My usage of this admittedly unusual - I wouldn't expect most people to be doing things this way.  

I guess the most common case in web dev would be to slurp the whole SQL result into an array of struct, then either convert that to json for output .... or pass the whole struct + arrays through a template for rendering.

**Comment by karlseguin** [comment]
`row.get(pg.Iterator(T), col)` is now supported.

The `to` and `mapper` behavior will now map an array column to an `pg.Iterator(T)` field.

In cases where to/mapper is given a custom allocator, `deinit(allocator)` must be called on the iterator.

**Comment by zigster64** [comment]
Thx, that is working for me, all good.

There is a separate memory allocation issue though - will raise a separate issue + patch soon
