### ISSUE TITLE
named params?

### ISSUE THREAD

**Issue by sdykae** [karlseguin/pg.zig#29]
is there a way to query with named params with the semicolon notation :param1
`select * from table where id = :param1`

**Comment by karlseguin** [comment]
No. It isn't something I think I want to add. PostgreSQL doesn't support this itself - it only supports positional parameters. The client/library has to do the transformation from named parameters -> positional itself. This means parsing the statement and doing the substitution.

**Comment by sdykae** [comment]
understood thanks
