### ISSUE TITLE
Would this be the recommended way to create transactions ?

### ISSUE THREAD

**Issue by crat1985** [karlseguin/pg.zig#35]
In Rust, I used SQLx which has a builtin begin() function to handle transactions and rollback if the transaction hasn't been committed, but I guess I can just do that because of Zig `defer` and `errdefer` keywords right ?

```zig
const rows_affected = try db_inner.exec("BEGIN", .{});
errdefer _ = db_inner.exec("ROLLBACK", .{}) catch unreachable;
defer _ = db_inner.exec("COMMIT", .{}) catch unreachable;
```

And it's even better than with SQLx because it makes it hard to forget to commit a transaction.

**Comment by karlseguin** [comment]
There is a is a conn.begin/commit/rollback. They just do what you're doing here:

```zig
    pub fn begin(self: *Conn) !void {
        self._state = .transaction;
        _ = try self.execOpts("begin", .{}, .{});
    }

    pub fn commit(self: *Conn) !void {
        _ = try self.execOpts("commit", .{}, .{});
    }

    pub fn rollback(self: *Conn) !void {
        _ = try self.execOpts("rollback", .{}, .{});
    }
```

I assume your `db_inner` is a `*pg.Conn`. If it's a `pg.Pool`, then what you're doing wouldn't work since each `exec` would execute against its own, potentially different, connection.


I tend to like the callback/closure approach to this, something like:

```
pg.transaction((tx) => {
  try tx.exec(...)
  try tx.exec(...)
);
```

But Zig, having no closure, can't really provide that kind of API.

**Comment by crat1985** [comment]
Great !
`db_inner` is a Pool 😅
I didn't know it already existed because  I didn't see it in the examples nor in the Pool (which is logical for the reasons you just gave me) 😅

**Comment by crat1985** [comment]
> Great ! `db_inner` is a Pool 😅 I didn't know it already existed because I didn't see it in the examples nor in the Pool (which is logical for the reasons you just gave me) 😅
> 
> That code is better 😅
> 
> ```zig
> var db_inner = try db.new(arena_allocator);
> 
> var conn = try db_inner.acquire();
> defer conn.release();
> 
> const rows_affected = try conn.begin();
> errdefer conn.rollback() catch unreachable;
> defer conn.commit() catch unreachable;
> ```

**Little note :** This doesn't work because it commits **and** rollbacks if there is an error

**Comment by karlseguin** [comment]
don't defer the commit:

```
conn.begin()
errdefer conn.rollback()
conn.exec()
conn.exec()
conn.commit()
```

**Comment by crat1985** [comment]
> don't defer the commit:
> 
> ```
> conn.begin()
> errdefer conn.rollback()
> conn.exec()
> conn.exec()
> conn.commit()
> ```

Yeah I have just noticed that thanks 💯
My connection on my computer is so bad that I didn't see your answer before editing 😂 (but it works perfectly on my phone which makes no sense)
