### ISSUE TITLE
Rollback transaction after a failed query seems to never work

### ISSUE THREAD

**Issue by richard-powers** [karlseguin/pg.zig#45]
If a query fails during a transaction, the connection state is set to `fail`. This prevents `conn.rollback()` from working, because `self.canQuery()` will always return false.

I'm currently trying to rollback if there's a unique constraint error (based on data a user provides to our REST API). I tried manually setting the connection state to `transaction` when this error is hit as a work-around, but it feels a bit hacky having to do that manually from outside the library.

**Comment by karlseguin** [comment]
I looked at a few different libraries to see how they handle this. Seems like they have a pretty generous "exec" and never stop a query from being executed, even if the state is failed/unknown. I'm not sure I like the idea of this being the default, so for now, I've special-cased `rollback`. It'll always try to issue the rollback command, regardless of the connection state.

**Comment by richard-powers** [comment]
Thanks for doing this!

Would it be possible to backport this fix for zig 0.13.0? We're using that version in production as it's the stable release.

**Comment by karlseguin** [comment]
I merged master back into the 0.13 branch and made it compatible with Zig 0.13 again. The only other major changes was to the row -> struct mapping to support arrays and such.

**Comment by richard-powers** [comment]
Thank you!
