### ISSUE TITLE
Array of enum is not supported

### ISSUE THREAD

**Issue by gyongph** [karlseguin/pg.zig#47]
```zig
const CustomerInfo = enum{
    profile,
    address,
};
const Application = struct {
  name: [] const u8,
  description: [] const u8,
  requirements: [] CustomerInfo,
}
``` 
`error: cannot get value of type modules.application.types.CustomerInfo
    @compileError("cannot get value of type " ++ @typeName(T));`

**Comment by karlseguin** [comment]
Should be fixed in both the master and zig-0.13 branches.
