### ISSUE TITLE
How to re-use acquired connection?

### ISSUE THREAD

**Issue by gyongph** [karlseguin/pg.zig#51]
Is there a way to reuse the connection after retrieving a record? For example, in a scenario where you retrieve the record, perform some checks, and then make an update.

**Comment by karlseguin** [comment]
Not sure what you're trying to do, but once you have a connection from a pool, you can re-use it for multiple queries.

What you can't do is execute a query while you have an open result/row. To do that, you need another query from the pool. As far as I know, this is simply not possible with PostgreSQL, but if you know of a driver that allows it, let me know and I'll try to see what they're doing.

**Comment by gyongph** [comment]
Got it! If I deinit the row or result, I can reuse the connection.
