### ISSUE TITLE
build.zig.zon "error: UnsupportedUrlScheme" Zig 0.11

### ISSUE THREAD

**Issue by emastho** [karlseguin/pg.zig#9]
Really thankful for your amazing work :)

What am I doing wrong?
May it be that git+url is not supported in Zig 0.11?

```zig
.{
    .name = "Learning",
    .version = "0.0.1",

    .dependencies = .{
        .pg = .{
            .url = "git+https://github.com/karlseguin/pg.zig#master",
        }
    }
}
```

`.tar.gz` libraries are working fine for me

**Comment by karlseguin** [comment]
You can use:

```
.pg = .{
  .url = "https://github.com/karlseguin/pg.zig/archive/zig-0.11.tar.gz",
  .hash = "1220337202642ee66408a35f254549f22cf3a096c6fa6c28e6f87a0161d5a6c0f4ab"
}
```

**Comment by emastho** [comment]
> You can use:
> 
> ```
> .pg = .{
>   .url = "https://github.com/karlseguin/pg.zig/archive/zig-0.11.tar.gz",
>   .hash = "1220337202642ee66408a35f254549f22cf3a096c6fa6c28e6f87a0161d5a6c0f4ab"
> }
> ```

Works, thank you :)
